---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.4
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: alpine:3.6
      containers:
      - name: podinfod
        image: stefanprodan/podinfo:1.4.4
