---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
  annotations:
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: Lock deployment in production
    flux.weave.works/locked_user: Alfonso Acosta <fons@weave.works>
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: alpine:3.5
      containers:
      - name: podinfod
        image: stefanprodan/podinfo:1.3.2
